#!/usr/bin/env groovy

node{

	stage('checkout'){
	    git url: 'https://github.com/AdrianNwajuobi1991/General-Purpose-Software-Applications.git'
	}
	
	stage('build'){
		def antHome = tool 'ant'
		bat "${antHome}/bin/ant ./StandAlone_GeoCodingAPI_Client/build.xml"
	}
	
}