#!/usr/bin/env groovy

node{

	stage('checkout'){
	    git url: 'https://github.com/AdrianNwajuobi1991/General-Purpose-Software-Applications/tree/master/StandAlone_GeoCodingAPI_Client'
	}
	
	stage('build'){
		echo 'building'
	}
	
}