#!/usr/bin/env groovy

node{

	stage('checkout'){
	    git url: 'https://github.com/AdrianNwajuobi1991/General-Purpose-Software-Applications.git'
	}
	
	stage('build'){
		def mvnHome = tool 'm2'
		bat "${mvnHome}/bin/mvn build -f./reverse-geocode/pom.xml -package"
	}
	
	stage('Results') {
      archiveArtifacts './reverse-geocode/target/*.jar'
   }
   
   stage('Publish') {
        nexusPublisher nexusInstanceId: 'test_nexus_repository_manager_server', nexusRepositoryId: 'test_repo_jenkins', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: 'StandAlone_GeoCodingAPI_Client/dist/StandAlone_GeocodingAPI_Client.jar']], mavenCoordinate: [artifactId: 'standalone-client', groupId: 'gov.bep.demoprojects', packaging: 'jar', version: '1.1']]]
   } 
}