#!/usr/bin/env groovy

node{

	stage('checkout'){
	    git url: 'https://github.com/AdrianNwajuobi1991/General-Purpose-Software-Applications.git'
	}
	
	stage('build'){
		def antHome = tool 'ant'
		bat "${antHome}/bin/ant -buildfile ./StandAlone_GeoCodingAPI_Client/build.xml"
	}
	
	stage('Results') {
      archiveArtifacts 'StandAlone_GeoCodingAPI_Client/dist/*.*'
   }
   
   stage('Publish') {
        nexusPublisher nexusInstanceId: 'test_nexus_repository_manager_server', nexusRepositoryId: 'test_repo_jenkins', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: 'StandAlone_GeoCodingAPI_Client/dist/StandAlone_GeocodingAPI_Client.jar']], mavenCoordinate: [artifactId: 'standalone-client', groupId: 'gov.bep.demoprojects', packaging: 'jar', version: '1.1']]]
   } 
}