#!/usr/bin/env groovy

node{

	stage('checkout'){
	    git url: 'https://github.com/AdrianNwajuobi1991/General-Purpose-Software-Applications.git'
	}
	
	stage('build'){
		dir('./reverse-geocode') {
    		def mvnHome = tool 'm2'
			bat 'pwd'
			bat "${mvnHome}/bin/mvn package"
		}
	}
	
	stage('Results') {
      archiveArtifacts './target/*.jar'
   }
   
   stage('Publish') {
        nexusPublisher nexusInstanceId: 'test_nexus_repository_manager_server', nexusRepositoryId: 'test_repo_jenkins', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: 'reverse-geocode/target/reverse-geocode-0.0.1-SNAPSHOT.jar']], mavenCoordinate: [artifactId: 'reverse-geocode-client', groupId: 'gov.bep.demoprojects', packaging: 'jar', version: '1.1']]]
   } 
}